# Generated by Django 2.1.3 on 2019-03-10 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Extra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bodyweight', models.CharField(choices=[('W87+', "Women's 87Kg+"), ('W87', "Women's 87Kg"), ('W76', "Women's 76kg"), ('W71', "Women's 71kg"), ('W64', "Women's 64kg"), ('W59', "Women's 59kg"), ('W55', "Women's 59kg"), ('W49', "Women's 49kg"), ('M109+', "Men's 109kg+"), ('M109+', "Men's 109Kg"), ('M102', "Men's 102Kg+"), ('M96', "Men's 96kg"), ('M89', "Men's 89kg"), ('M81', "Men's 81kg"), ('M73', "Men's 73kg"), ('M67', "Men's 67kg"), ('M61', "Men's 61kg"), ('M56', "Men's 56kg")], default='Please choose a bodyweight', max_length=6)),
                ('date_of_birth', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExtraDetail',
        ),
        migrations.AddField(
            model_name='programme',
            name='exercise',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='Users.Exercise'),
        ),
        migrations.AddField(
            model_name='programme',
            name='sets',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='Users.Sets'),
        ),
        migrations.AlterField(
            model_name='programme',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
