# Generated by Django 2.1.3 on 2019-03-19 13:10

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0003_auto_20190318_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='programme',
            name='notes',
            field=models.CharField(default='insert notes here', max_length=1000),
        ),
        migrations.AddField(
            model_name='programme',
            name='reps',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='programme',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
        migrations.AlterField(
            model_name='extra',
            name='bodyweight',
            field=models.CharField(choices=[('W87+', "Women's 87Kg+"), ('W87', "Women's 87Kg"), ('W76', "Women's 76kg"), ('W71', "Women's 71kg"), ('W64', "Women's 64kg"), ('W59', "Women's 59kg"), ('W55', "Women's 55kg"), ('W49', "Women's 49kg"), ('M109+', "Men's 109kg+"), ('M109+', "Men's 109Kg"), ('M102', "Men's 102Kg+"), ('M96', "Men's 96kg"), ('M89', "Men's 89kg"), ('M81', "Men's 81kg"), ('M73', "Men's 73kg"), ('M67', "Men's 67kg"), ('M61', "Men's 61kg"), ('M56', "Men's 56kg")], default='Please choose a bodyweight', max_length=6),
        ),
        migrations.AlterField(
            model_name='programme',
            name='sets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='sets',
            name='notes',
            field=models.CharField(default='insert notes here', max_length=1000),
        ),
        migrations.AlterField(
            model_name='sets',
            name='reps',
            field=models.IntegerField(default=3),
        ),
        migrations.AlterField(
            model_name='sets',
            name='sets',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)]),
        ),
        migrations.AlterField(
            model_name='sets',
            name='weight',
            field=models.DecimalField(decimal_places=2, default=10, max_digits=5),
        ),
    ]
